"""refine_models_and_caching

Revision ID: 064763f591f9
Revises: e8142f92c27c
Create Date: 2026-06-14 00:49:32.366260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '064763f591f9'
down_revision: Union[str, Sequence[str], None] = 'e8142f92c27c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_runs', sa.Column('run_type', sa.String(length=32), nullable=True))
    op.execute("UPDATE research_runs SET run_type = type")
    op.alter_column('research_runs', 'run_type', nullable=False)
    
    op.add_column('research_runs', sa.Column('run_hash', sa.String(length=64), nullable=True))
    op.add_column('research_runs', sa.Column('artifact_size_bytes', sa.BigInteger(), nullable=True))
    op.drop_index(op.f('idx_runs_strat_type_created'), table_name='research_runs')
    op.create_index('idx_runs_strat_type_created', 'research_runs', ['strategy_id', 'run_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_research_runs_run_hash'), 'research_runs', ['run_hash'], unique=False)
    op.drop_column('research_runs', 'type')
    op.drop_constraint(op.f('strategies_golden_version_id_fkey'), 'strategies', type_='foreignkey')
    op.drop_column('strategies', 'golden_version_id')
    
    op.add_column('strategy_versions', sa.Column('is_golden', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_versions', 'is_golden')
    op.add_column('strategies', sa.Column('golden_version_id', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('strategies_golden_version_id_fkey'), 'strategies', 'strategy_versions', ['golden_version_id'], ['id'], ondelete='SET NULL')
    
    op.add_column('research_runs', sa.Column('type', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.execute("UPDATE research_runs SET type = run_type")
    op.alter_column('research_runs', 'type', nullable=False)
    
    op.drop_index(op.f('ix_research_runs_run_hash'), table_name='research_runs')
    op.drop_index('idx_runs_strat_type_created', table_name='research_runs')
    op.create_index(op.f('idx_runs_strat_type_created'), 'research_runs', ['strategy_id', 'type', 'created_at'], unique=False)
    op.drop_column('research_runs', 'artifact_size_bytes')
    op.drop_column('research_runs', 'run_hash')
    op.drop_column('research_runs', 'run_type')
    # ### end Alembic commands ###
