"""Added research models and backtest fields

Revision ID: 124dcedca8bf
Revises: 11d3f2b5037e
Create Date: 2026-06-09 20:01:10.436947

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "124dcedca8bf"
down_revision: Union[str, Sequence[str], None] = "11d3f2b5037e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "optimization_runs",
        sa.Column("id", sa.String(length=150), nullable=False),
        sa.Column("user_id", sa.String(length=150), nullable=False),
        sa.Column("strategy_id", sa.String(length=150), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("search_type", sa.String(length=20), nullable=False),
        sa.Column("objective", sa.String(length=50), nullable=False),
        sa.Column("max_runs", sa.Integer(), nullable=False),
        sa.Column("initial_capital", sa.Float(), nullable=False),
        sa.Column("parameter_space_json", sa.JSON(), nullable=False),
        sa.Column("constraints_json", sa.JSON(), nullable=True),
        sa.Column("best_result_json", sa.JSON(), nullable=True),
        sa.Column("leaderboard_json", sa.JSON(), nullable=True),
        sa.Column("progress_json", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("credits_used", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["strategy_id"], ["strategies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_optimization_runs_id"), "optimization_runs", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_optimization_runs_strategy_id"),
        "optimization_runs",
        ["strategy_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_optimization_runs_user_id"),
        "optimization_runs",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "walkforward_runs",
        sa.Column("id", sa.String(length=150), nullable=False),
        sa.Column("user_id", sa.String(length=150), nullable=False),
        sa.Column("strategy_id", sa.String(length=150), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("window_type", sa.String(length=20), nullable=False),
        sa.Column("objective", sa.String(length=50), nullable=False),
        sa.Column("initial_capital", sa.Float(), nullable=False),
        sa.Column("window_config_json", sa.JSON(), nullable=False),
        sa.Column("summary_json", sa.JSON(), nullable=True),
        sa.Column("progress_json", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("credits_used", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["strategy_id"], ["strategies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_walkforward_runs_id"), "walkforward_runs", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_walkforward_runs_strategy_id"),
        "walkforward_runs",
        ["strategy_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_walkforward_runs_user_id"),
        "walkforward_runs",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "montecarlo_runs",
        sa.Column("id", sa.String(length=150), nullable=False),
        sa.Column("user_id", sa.String(length=150), nullable=False),
        sa.Column("strategy_id", sa.String(length=150), nullable=False),
        sa.Column("source_backtest_id", sa.String(length=150), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("simulation_count", sa.Integer(), nullable=False),
        sa.Column("method", sa.String(length=30), nullable=False),
        sa.Column("random_seed", sa.Integer(), nullable=True),
        sa.Column("summary_json", sa.JSON(), nullable=True),
        sa.Column("progress_json", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("credits_used", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_backtest_id"], ["backtests.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["strategy_id"], ["strategies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_montecarlo_runs_id"), "montecarlo_runs", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_montecarlo_runs_source_backtest_id"),
        "montecarlo_runs",
        ["source_backtest_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_montecarlo_runs_strategy_id"),
        "montecarlo_runs",
        ["strategy_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_montecarlo_runs_user_id"), "montecarlo_runs", ["user_id"], unique=False
    )
    op.add_column(
        "backtests",
        sa.Column(
            "status", sa.String(length=20), server_default="PENDING", nullable=False
        ),
    )
    op.add_column("backtests", sa.Column("progress_json", sa.JSON(), nullable=True))
    op.add_column(
        "backtests",
        sa.Column("credits_used", sa.Integer(), server_default="5", nullable=False),
    )
    op.add_column(
        "backtests", sa.Column("started_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "backtests",
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "backtests",
        "metrics_json",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "backtests",
        "charting_json",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "backtests",
        "charting_json",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "backtests",
        "metrics_json",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    op.drop_column("backtests", "completed_at")
    op.drop_column("backtests", "started_at")
    op.drop_column("backtests", "credits_used")
    op.drop_column("backtests", "progress_json")
    op.drop_column("backtests", "status")
    op.drop_index(op.f("ix_montecarlo_runs_user_id"), table_name="montecarlo_runs")
    op.drop_index(op.f("ix_montecarlo_runs_strategy_id"), table_name="montecarlo_runs")
    op.drop_index(
        op.f("ix_montecarlo_runs_source_backtest_id"), table_name="montecarlo_runs"
    )
    op.drop_index(op.f("ix_montecarlo_runs_id"), table_name="montecarlo_runs")
    op.drop_table("montecarlo_runs")
    op.drop_index(op.f("ix_walkforward_runs_user_id"), table_name="walkforward_runs")
    op.drop_index(
        op.f("ix_walkforward_runs_strategy_id"), table_name="walkforward_runs"
    )
    op.drop_index(op.f("ix_walkforward_runs_id"), table_name="walkforward_runs")
    op.drop_table("walkforward_runs")
    op.drop_index(op.f("ix_optimization_runs_user_id"), table_name="optimization_runs")
    op.drop_index(
        op.f("ix_optimization_runs_strategy_id"), table_name="optimization_runs"
    )
    op.drop_index(op.f("ix_optimization_runs_id"), table_name="optimization_runs")
    op.drop_table("optimization_runs")
    # ### end Alembic commands ###
