"""add_progress_json

Revision ID: 15f458c6ea12
Revises: 2b7ab5878847
Create Date: 2026-06-13 00:45:09.396389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15f458c6ea12'
down_revision: Union[str, Sequence[str], None] = '2b7ab5878847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_runs', sa.Column('progress_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_runs', 'progress_json')
    # ### end Alembic commands ###
