"""unified_research_runs

Revision ID: 2b7ab5878847
Revises: 9e699642eb8f
Create Date: 2026-06-13 00:43:26.542012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b7ab5878847'
down_revision: Union[str, Sequence[str], None] = '9e699642eb8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_runs',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('strategy_id', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('report_version', sa.String(length=32), nullable=True),
    sa.Column('metadata_s3_key', sa.String(), nullable=True),
    sa.Column('report_s3_key', sa.String(), nullable=True),
    sa.Column('dataset_s3_key', sa.String(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_runs_id'), 'research_runs', ['id'], unique=True)
    op.create_index(op.f('ix_research_runs_strategy_id'), 'research_runs', ['strategy_id'], unique=False)
    op.create_table('strategy_latest_results',
    sa.Column('strategy_id', sa.String(length=150), nullable=False),
    sa.Column('latest_backtest_id', sa.String(length=150), nullable=True),
    sa.Column('latest_optimization_id', sa.String(length=150), nullable=True),
    sa.Column('latest_walkforward_id', sa.String(length=150), nullable=True),
    sa.Column('latest_montecarlo_id', sa.String(length=150), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['latest_backtest_id'], ['research_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['latest_montecarlo_id'], ['research_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['latest_optimization_id'], ['research_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['latest_walkforward_id'], ['research_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('strategy_id')
    )
    op.drop_index(op.f('ix_montecarlo_runs_id'), table_name='montecarlo_runs')
    op.drop_index(op.f('ix_montecarlo_runs_source_backtest_id'), table_name='montecarlo_runs')
    op.drop_index(op.f('ix_montecarlo_runs_strategy_id'), table_name='montecarlo_runs')
    op.drop_index(op.f('ix_montecarlo_runs_user_id'), table_name='montecarlo_runs')
    op.drop_table('montecarlo_runs')
    op.drop_index(op.f('ix_backtests_id'), table_name='backtests')
    op.drop_index(op.f('ix_backtests_strategy_id'), table_name='backtests')
    op.drop_table('backtests')
    op.drop_index(op.f('ix_optimization_runs_id'), table_name='optimization_runs')
    op.drop_index(op.f('ix_optimization_runs_strategy_id'), table_name='optimization_runs')
    op.drop_index(op.f('ix_optimization_runs_user_id'), table_name='optimization_runs')
    op.drop_table('optimization_runs')
    op.drop_index(op.f('ix_walkforward_runs_id'), table_name='walkforward_runs')
    op.drop_index(op.f('ix_walkforward_runs_strategy_id'), table_name='walkforward_runs')
    op.drop_index(op.f('ix_walkforward_runs_user_id'), table_name='walkforward_runs')
    op.drop_table('walkforward_runs')
    op.add_column('strategies', sa.Column('is_template', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('strategies', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'is_archived')
    op.drop_column('strategies', 'is_template')
    op.create_table('walkforward_runs',
    sa.Column('id', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('strategy_id', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('window_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('objective', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('initial_capital', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('window_config_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('summary_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('progress_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('credits_used', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('walkforward_runs_strategy_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('walkforward_runs_pkey'))
    )
    op.create_index(op.f('ix_walkforward_runs_user_id'), 'walkforward_runs', ['user_id'], unique=False)
    op.create_index(op.f('ix_walkforward_runs_strategy_id'), 'walkforward_runs', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_walkforward_runs_id'), 'walkforward_runs', ['id'], unique=True)
    op.create_table('montecarlo_runs',
    sa.Column('id', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('strategy_id', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('source_backtest_id', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('simulation_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('method', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('random_seed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('summary_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('progress_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('credits_used', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['source_backtest_id'], ['backtests.id'], name=op.f('montecarlo_runs_source_backtest_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('montecarlo_runs_strategy_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('montecarlo_runs_pkey'))
    )
    op.create_index(op.f('ix_montecarlo_runs_user_id'), 'montecarlo_runs', ['user_id'], unique=False)
    op.create_index(op.f('ix_montecarlo_runs_strategy_id'), 'montecarlo_runs', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_montecarlo_runs_source_backtest_id'), 'montecarlo_runs', ['source_backtest_id'], unique=False)
    op.create_index(op.f('ix_montecarlo_runs_id'), 'montecarlo_runs', ['id'], unique=True)
    op.create_table('backtests',
    sa.Column('id', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('strategy_id', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('initial_capital', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('10000.0'), autoincrement=False, nullable=False),
    sa.Column('metrics_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('charting_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False),
    sa.Column('progress_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('credits_used', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('backtests_strategy_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('backtests_pkey'))
    )
    op.create_index(op.f('ix_backtests_strategy_id'), 'backtests', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_backtests_id'), 'backtests', ['id'], unique=True)
    op.create_table('optimization_runs',
    sa.Column('id', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('strategy_id', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('search_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('objective', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('max_runs', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('initial_capital', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('parameter_space_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('constraints_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('best_result_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('leaderboard_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('progress_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('credits_used', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('optimization_runs_strategy_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('optimization_runs_pkey'))
    )
    op.create_index(op.f('ix_optimization_runs_user_id'), 'optimization_runs', ['user_id'], unique=False)
    op.create_index(op.f('ix_optimization_runs_strategy_id'), 'optimization_runs', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_optimization_runs_id'), 'optimization_runs', ['id'], unique=True)
    op.drop_table('strategy_latest_results')
    op.drop_index(op.f('ix_research_runs_strategy_id'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_id'), table_name='research_runs')
    op.drop_table('research_runs')
    # ### end Alembic commands ###
