"""Add artifact_manifest to ResearchRun

Revision ID: 528c25f6e08a
Revises: 064763f591f9
Create Date: 2026-06-28 13:39:53.261642

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "528c25f6e08a"
down_revision: Union[str, Sequence[str], None] = "064763f591f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "research_runs", sa.Column("artifact_manifest", sa.JSON(), nullable=True)
    )
    op.drop_column("research_runs", "report_s3_key")
    op.drop_column("research_runs", "metadata_s3_key")
    op.drop_column("research_runs", "dataset_s3_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "research_runs",
        sa.Column("dataset_s3_key", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "research_runs",
        sa.Column("metadata_s3_key", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "research_runs",
        sa.Column("report_s3_key", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("research_runs", "artifact_manifest")
    # ### end Alembic commands ###
