"""add_live_trading_sessions

Revision ID: 8a50093d76eb
Revises: 3b3cde9ef213
Create Date: 2026-07-02 23:09:22.019835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a50093d76eb'
down_revision: Union[str, Sequence[str], None] = '3b3cde9ef213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credential_audit_logs',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('user_id', sa.String(length=150), nullable=False),
    sa.Column('credential_id', sa.String(length=150), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credential_audit_logs_credential_id'), 'credential_audit_logs', ['credential_id'], unique=False)
    op.create_index(op.f('ix_credential_audit_logs_id'), 'credential_audit_logs', ['id'], unique=True)
    op.create_index(op.f('ix_credential_audit_logs_user_id'), 'credential_audit_logs', ['user_id'], unique=False)
    op.create_table('strategy_events',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('strategy_run_id', sa.String(length=150), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_version', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_run_type', 'strategy_events', ['strategy_run_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_strategy_events_id'), 'strategy_events', ['id'], unique=True)
    op.create_index(op.f('ix_strategy_events_strategy_run_id'), 'strategy_events', ['strategy_run_id'], unique=False)
    op.create_table('broker_credentials',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('user_id', sa.String(length=150), nullable=False),
    sa.Column('exchange', sa.Enum('DELTA', 'BINANCE', 'BYBIT', 'OKX', name='exchange'), nullable=False),
    sa.Column('account_label', sa.String(length=100), nullable=False),
    sa.Column('api_key_encrypted', sa.String(length=512), nullable=False),
    sa.Column('api_secret_encrypted', sa.String(length=512), nullable=False),
    sa.Column('passphrase_encrypted', sa.String(length=512), nullable=True),
    sa.Column('is_testnet', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exchange', 'account_label', name='uq_user_exchange_label')
    )
    op.create_index(op.f('ix_broker_credentials_id'), 'broker_credentials', ['id'], unique=True)
    op.create_index(op.f('ix_broker_credentials_user_id'), 'broker_credentials', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.String(length=150), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=100), nullable=True),
    sa.Column('telegram_enabled', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('paper_alerts', sa.Boolean(), nullable=False),
    sa.Column('live_alerts', sa.Boolean(), nullable=False),
    sa.Column('stoploss_alerts', sa.Boolean(), nullable=False),
    sa.Column('tp_alerts', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('live_trading_sessions',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('strategy_id', sa.String(length=150), nullable=False),
    sa.Column('version_id', sa.String(length=150), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('broker', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('error_msg', sa.String(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_processed_timestamp', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['strategy_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_live_sessions_strategy_status', 'live_trading_sessions', ['strategy_id', 'status'], unique=False)
    op.create_index(op.f('ix_live_trading_sessions_id'), 'live_trading_sessions', ['id'], unique=True)
    op.create_index(op.f('ix_live_trading_sessions_status'), 'live_trading_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_live_trading_sessions_strategy_id'), 'live_trading_sessions', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_live_trading_sessions_version_id'), 'live_trading_sessions', ['version_id'], unique=False)
    op.create_index('uq_strategy_running_session', 'live_trading_sessions', ['strategy_id'], unique=True, postgresql_where=sa.text("status = 'RUNNING'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_strategy_running_session', table_name='live_trading_sessions', postgresql_where=sa.text("status = 'RUNNING'"))
    op.drop_index(op.f('ix_live_trading_sessions_version_id'), table_name='live_trading_sessions')
    op.drop_index(op.f('ix_live_trading_sessions_strategy_id'), table_name='live_trading_sessions')
    op.drop_index(op.f('ix_live_trading_sessions_status'), table_name='live_trading_sessions')
    op.drop_index(op.f('ix_live_trading_sessions_id'), table_name='live_trading_sessions')
    op.drop_index('idx_live_sessions_strategy_status', table_name='live_trading_sessions')
    op.drop_table('live_trading_sessions')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_broker_credentials_user_id'), table_name='broker_credentials')
    op.drop_index(op.f('ix_broker_credentials_id'), table_name='broker_credentials')
    op.drop_table('broker_credentials')
    op.drop_index(op.f('ix_strategy_events_strategy_run_id'), table_name='strategy_events')
    op.drop_index(op.f('ix_strategy_events_id'), table_name='strategy_events')
    op.drop_index('idx_events_run_type', table_name='strategy_events')
    op.drop_table('strategy_events')
    op.drop_index(op.f('ix_credential_audit_logs_user_id'), table_name='credential_audit_logs')
    op.drop_index(op.f('ix_credential_audit_logs_id'), table_name='credential_audit_logs')
    op.drop_index(op.f('ix_credential_audit_logs_credential_id'), table_name='credential_audit_logs')
    op.drop_table('credential_audit_logs')
    # ### end Alembic commands ###
