"""remove legacy exchange symbol leverage from backtest

Revision ID: 9e699642eb8f
Revises: 124dcedca8bf
Create Date: 2026-06-09 22:09:21.078122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e699642eb8f'
down_revision: Union[str, Sequence[str], None] = '124dcedca8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtests', 'symbol')
    op.drop_column('backtests', 'exchange')
    op.drop_column('backtests', 'leverage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtests', sa.Column('leverage', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('backtests', sa.Column('exchange', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('backtests', sa.Column('symbol', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
