"""add_institutional_traceability

Revision ID: e8142f92c27c
Revises: f598e4e75966
Create Date: 2026-06-13 01:48:57.251412

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e8142f92c27c"
down_revision: Union[str, Sequence[str], None] = "f598e4e75966"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_notes",
        sa.Column("id", sa.String(length=150), nullable=False),
        sa.Column("strategy_id", sa.String(length=150), nullable=False),
        sa.Column("run_id", sa.String(length=150), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["research_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["strategy_id"], ["strategies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_research_notes_id"), "research_notes", ["id"], unique=True)
    op.create_index(
        op.f("ix_research_notes_run_id"), "research_notes", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_research_notes_strategy_id"),
        "research_notes",
        ["strategy_id"],
        unique=False,
    )
    op.add_column(
        "research_runs",
        sa.Column("parent_run_id", sa.String(length=150), nullable=True),
    )
    op.create_index(
        op.f("ix_research_runs_parent_run_id"),
        "research_runs",
        ["parent_run_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "research_runs",
        "research_runs",
        ["parent_run_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "strategies",
        sa.Column("golden_version_id", sa.String(length=150), nullable=True),
    )
    op.create_foreign_key(
        None,
        "strategies",
        "strategy_versions",
        ["golden_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "strategy_versions", sa.Column("label", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "strategy_versions",
        sa.Column(
            "approval_status",
            sa.String(length=32),
            server_default="DRAFT",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("strategy_versions", "approval_status")
    op.drop_column("strategy_versions", "label")
    op.drop_constraint(None, "strategies", type_="foreignkey")
    op.drop_column("strategies", "golden_version_id")
    op.drop_constraint(None, "research_runs", type_="foreignkey")
    op.drop_index(op.f("ix_research_runs_parent_run_id"), table_name="research_runs")
    op.drop_column("research_runs", "parent_run_id")
    op.drop_index(op.f("ix_research_notes_strategy_id"), table_name="research_notes")
    op.drop_index(op.f("ix_research_notes_run_id"), table_name="research_notes")
    op.drop_index(op.f("ix_research_notes_id"), table_name="research_notes")
    op.drop_table("research_notes")
    # ### end Alembic commands ###
