"""add_strategy_versioning

Revision ID: f598e4e75966
Revises: 15f458c6ea12
Create Date: 2026-06-13 01:33:19.535155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f598e4e75966'
down_revision: Union[str, Sequence[str], None] = '15f458c6ea12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_versions',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('strategy_id', sa.String(length=150), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('commit_message', sa.Text(), nullable=True),
    sa.Column('canvas_json', sa.JSON(), nullable=True),
    sa.Column('source_code', sa.Text(), nullable=True),
    sa.Column('compiled_code', sa.Text(), nullable=False),
    sa.Column('compiled_hash', sa.String(length=64), nullable=False),
    sa.Column('is_code_modified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_strategy_versions_strat_ver', 'strategy_versions', ['strategy_id', 'version'], unique=True)
    op.create_index(op.f('ix_strategy_versions_id'), 'strategy_versions', ['id'], unique=True)
    op.create_index(op.f('ix_strategy_versions_strategy_id'), 'strategy_versions', ['strategy_id'], unique=False)
    op.add_column('research_runs', sa.Column('compiled_hash', sa.String(length=64), nullable=True))
    op.add_column('research_runs', sa.Column('strategy_version_id', sa.String(length=150), nullable=True))
    op.create_index('idx_runs_status', 'research_runs', ['status'], unique=False)
    op.create_index('idx_runs_strat_fav', 'research_runs', ['strategy_id', 'is_favorite'], unique=False)
    op.create_index('idx_runs_strat_type_created', 'research_runs', ['strategy_id', 'type', 'created_at'], unique=False)
    op.create_index(op.f('ix_research_runs_strategy_version_id'), 'research_runs', ['strategy_version_id'], unique=False)
    op.create_foreign_key(None, 'research_runs', 'strategy_versions', ['strategy_version_id'], ['id'], ondelete='SET NULL')
    op.add_column('strategies', sa.Column('strategy_type', sa.String(length=20), server_default='VISUAL', nullable=False))
    op.add_column('strategies', sa.Column('source_code', sa.String(), nullable=True))
    op.add_column('strategies', sa.Column('compiled_hash', sa.String(length=64), nullable=True))
    op.add_column('strategies', sa.Column('current_version', sa.Integer(), server_default='0', nullable=False))
    op.add_column('strategies', sa.Column('has_unpublished_changes', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'has_unpublished_changes')
    op.drop_column('strategies', 'current_version')
    op.drop_column('strategies', 'compiled_hash')
    op.drop_column('strategies', 'source_code')
    op.drop_column('strategies', 'strategy_type')
    op.drop_constraint(None, 'research_runs', type_='foreignkey')
    op.drop_index(op.f('ix_research_runs_strategy_version_id'), table_name='research_runs')
    op.drop_index('idx_runs_strat_type_created', table_name='research_runs')
    op.drop_index('idx_runs_strat_fav', table_name='research_runs')
    op.drop_index('idx_runs_status', table_name='research_runs')
    op.drop_column('research_runs', 'strategy_version_id')
    op.drop_column('research_runs', 'compiled_hash')
    op.drop_index(op.f('ix_strategy_versions_strategy_id'), table_name='strategy_versions')
    op.drop_index(op.f('ix_strategy_versions_id'), table_name='strategy_versions')
    op.drop_index('idx_strategy_versions_strat_ver', table_name='strategy_versions')
    op.drop_table('strategy_versions')
    # ### end Alembic commands ###
